name: Test V3 Fee Bot Environment

on:
  workflow_dispatch:

jobs:
  covert_to_public_key:
    runs-on: ubuntu-latest
    environment: v3-fee-bot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Convert Private to Public Key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: cast wallet address --private-key $PRIVATE_KEY
